#!/usr/bin/env php
<?php

$loader = require __DIR__.'/vendor/autoload.php';
$loader->addPsr4('App\\', __DIR__ . '/app');

use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands
$application->add(new \App\Commands\TestCommand);

$application->run();
